source 'https://rubygems.org'
gem 'rails', '~> 4.1.7'
gem 'sqlite3', '~> 1.3.10'
gem 'rspec-rails', '~> 3.1.0'
gem 'pry', '~> 0.10.1'
gem 'pry-byebug', '~> 2.0.0'
gem 'perfect_money_merchant', path: '../..'

